version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: zest-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zestdb
    ports:
      - "3307:3306"

  app:
    build: .
    container_name: zest-product-api
    restart: always
    ports:
      - "8585:8585"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/zestdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Root@123
      SPRING_PROFILES_ACTIVE: docker